services:
  client:
    image: epickid976/react-client:latest
    ports:
      - "3002:3000"
    environment:
      - REACT_APP_SERVER_URL=ws://localhost:5002
    restart: always
    depends_on:
      - server

  server:
    image: epickid976/react-server:latest
    ports:
      - "5002:5000"
    environment:
      - PORT=${PORT:-5000}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    restart: always

